package com.comp2042.Inputs_Events;

/**
 * Represents the different types of input or gameplay events
 * that can occur during the game. These events are typically
 * generated by user input or automated game logic.
 */
public enum EventType {
    /**
     * Moves the active brick downward by one row.
     */
    DOWN,
    /**
     * Moves the active brick one cell to the left.
     */
    LEFT,
    /**
     * Moves the active brick one cell to the right.
     */
    RIGHT,
    /**
     * Rotates the active brick clockwise.
     */
    ROTATE,
    /**
     * Instantly drops the active brick to the lowest valid position.
     */
    HARD_DROP,
    /**
     * Holds the current brick or swaps it with the previously held brick.
     */
    HOLD
}
